travis:
  secure:
    BINSTAR_TOKEN: CdH6INIKk559CeNhWHSEIZuc5A5iDgokY3Gh/iesQV9IVNvVxYPykdsQGyVogEiEwoKzedQaHcnP02c7d4F8bsD2smYWX+JwZiSahDZk020MASSpuxEeiDmRjrO7+u5LkMKXcddzD4nh2RiJI/WbeUvTbNt8iBf/L21HlZp1Hp0GwO5IiqceBfvy/W6jDqVFPXfGtACmcZXHv4J78aT7E+sUYwIlR8YyjsBvnfrEc9UQf2bYtwjJwUIK+49c6LrxQnjl+fgLSF+F9YniEdPTVNFplIh8z3JSB/h2iD1qImj1Iy83RsZX2QcLlkb3sYTX9UXAMH4mfbeJUAuZLaLAtw7g1UgVFQXvXt7iL0+JefYaO2Ih77OmtKmmy67kk7LqE6WbUMIHgBFbajiMwx9k9UGqNJluaqiNgjhZaPU648AlOrdxNPZ8HF/cLWMcLwHN8HoqBbABCDS7I/h2yth3xbcx3G7JrR1sOq33zu1+I/k5N7Br6IqonC596Bn3+CynYDTAjYLtFt2Ium2npMRWpk5ncg7T9FrGJ6Vh1qeTSuzKVogp2KuDaBUB7McDJ47YfgxbI07YexGfcBme7IdAa/ia3SM5W63ayC5GBAh00SKhzYTtWaP4v4JKDiAisjykSdnupEv2UMsaoO5AtVzPm96KgbxvjBpMeC9AHUXsFZs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
